name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
        django-version: [3.1, 3.2]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q -e .
        echo "Python ${{ matrix.python-version }} -> Django ${{ matrix.django-version }}"
        sed -i '/Django==.*/d' ./requirements.txt # delete django dependency
        pip install -r requirements.txt
        python -m pip install "Django~=${{ matrix.django-version }}.0"
        echo "Django: `django-admin --version`"
        python --version
    - name: Run Tests
      run: |
        docker run --name manticore -v /tmp/:/var/lib/manticore -p 127.0.0.1:9306:9306 -d manticoresearch/manticore
        python ./manage.py test
        python ./manage.py test --parallel
